TrajectoryPlannerROS:

# 機器人配置參數
  max_vel_x: 0.5 # X 方向最大速度
  min_vel_x: -0.5 # X 方向最小速度

  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_x: 1.0 # X 加速限制
  acc_lim_y: 0.0 # Y 加速限制
  acc_lim_theta: 0.8 # 角速度加速限制

# 目標公差參數
  xy_goal_tolerance: 0 #0.002 #0.10
  yaw_goal_tolerance: 0 #0.001 #0.05

# 差速驅動機器人配置
# 是否是全向移動機器人
  holonomic_robot: false

# 前進模擬參數
  sim_time: 1.2 #0.8
  vx_samples: 120 #18 
  vtheta_samples: 180 #20 
  sim_granularity: 0.05
