local_costmap:
  global_frame: odom # Odometry coordinate frame
  robot_base_frame: base_footprint # Robot coordinate frame

  update_frequency: 10.0 # Costmap update frequency
  publish_frequency: 10.0 # Costmap publish frequency
  transform_tolerance: 0.5 # Timeout for waiting for coordinate transform publication

  static_map: false  # 不需要static map，可以提高導航性能
  rolling_window: true # 是否使用rolling window；默認為false。在靜態global map中，地圖不會改變
  width: 3 # 局部地圖的寬度（m）
  height: 3 # 局部地圖的高度（m）
  resolution: 0.05 # 局部地圖的解析度（m），通常與static map解析度一樣


