<robot name="car_laser" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- Lidar support properties -->
    <xacro:property name="support_length" value="0.025" /> <!-- Support length -->
    <xacro:property name="support_radius" value="0.01" />  <!-- Support radius -->
    <xacro:property name="support_x" value="0.0" />        <!-- Support mounting x coordinate -->
    <xacro:property name="support_y" value="0.0" />        <!-- Support mounting y coordinate -->
    <xacro:property name="support_z" value="${base_link_length / 2 + support_length / 2}" /> <!-- Support mounting z coordinate: chassis height / 2 + support height / 2 -->

    <xacro:property name="support_m" value="0.02" />       <!-- Support mass -->

    <link name="support">
        <visual>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="red">
                <color rgba="0.8 0.2 0.0 0.8" />
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>

        <xacro:cylinder_inertial_matrix m="${support_m}" r="${support_radius}" h="${support_length}" />
    </link>

    <joint name="support2base_link" type="fixed">
        <parent link="base_link" />
        <child link="support" />
        <origin xyz="${support_x} ${support_y} ${support_z}" />
    </joint>

    <gazebo reference="support">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- Lidar properties -->
    <xacro:property name="laser_length" value="0.05" /> <!-- Lidar length -->
    <xacro:property name="laser_radius" value="0.03" /> <!-- Lidar radius -->
    <xacro:property name="laser_x" value="0.0" />       <!-- Lidar mounting x coordinate -->
    <xacro:property name="laser_y" value="0.0" />       <!-- Lidar mounting y coordinate -->
    <xacro:property name="laser_z" value="${support_length / 2 + laser_length / 2}" /> <!-- Lidar mounting z coordinate: support height / 2 + lidar height / 2 -->

    <xacro:property name="laser_m" value="0.1" />       <!-- Lidar mass -->

    <!-- Lidar joint and link -->
    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${laser_m}" r="${laser_radius}" h="${laser_length}" />
    </link>

    <joint name="laser2support" type="fixed">
        <parent link="support" />
        <child link="laser" />
        <origin xyz="${laser_x} ${laser_y} ${laser_z}" />
    </joint>
    <gazebo reference="laser">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- Lidar plugin -->
    <gazebo reference="laser">
        <sensor type="ray" name="rplidar">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14159265</min_angle>
                        <max_angle>3.14159265</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_rplidar" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>laser</frameName>
            </plugin>
        </sensor>
    </gazebo>

</robot>
